// <auto-generated />
using System;
using IncludIA.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace IncludIA.Infrastructure.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    partial class OracleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncludIA.Domain.Entities.Candidato", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CANDIDATO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_CANDIDATO");
                });

            modelBuilder.Entity("IncludIA.Domain.Entities.Candidatura", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CANDIDATURA");

                    b.Property<string>("CandidatoId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("ID_CANDIDATO");

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_APLICACAO");

                    b.Property<string>("VagaMongoId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ID_VAGA_MONGO");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.ToTable("TB_CANDIDATURA");
                });

            modelBuilder.Entity("IncludIA.Domain.Entities.Candidatura", b =>
                {
                    b.HasOne("IncludIA.Domain.Entities.Candidato", "Candidato")
                        .WithMany("Candidaturas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("IncludIA.Domain.Entities.Candidato", b =>
                {
                    b.Navigation("Candidaturas");
                });
#pragma warning restore 612, 618
        }
    }
}
